### ISSUE TITLE
Report Error 😊

### ISSUE THREAD

**Issue by infernoshoot** [eXzacT/RePrimitive#2]
Report Error 😊
![999](https://user-images.githubusercontent.com/29793108/161938112-cb4394e4-5105-4039-82bd-832d30591bfd.PNG)

**Comment by eXzacT** [comment]
Hello, please check the previous reported issue. Do not download from
"Releases" but rather from "Code"

sri, 6. tra 2022. 11:02 infernoshoot ***@***.***> je napisao:

**Comment by eXzacT** [comment]
![Screenshot_2022-04-06-19-24-59-447_com android chrome](https://user-images.githubusercontent.com/49790173/162032805-56f05842-412b-46e6-9feb-e4d8118f0cec.jpg)

**Comment by infernoshoot** [comment]
> ![Screenshot_2022-04-06-19-24-59-447_com android chrome](https://user-images.githubusercontent.com/49790173/162032805-56f05842-412b-46e6-9feb-e4d8118f0cec.jpg)

Thank you

**Comment by eXzacT** [comment]
No worries :)

čet, 7. tra 2022. 06:17 infernoshoot ***@***.***> je napisao:
