### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by xz-blender** [eXzacT/RePrimitive#3]
Releases is v1.2
but addon was v1.1
and "Fix Rotation" operator not working on blender4.0.2
issue as:
<img width="795" alt="Snipaste_2024-03-13_04-17-03" src="https://github.com/eXzacT/RePrimitive/assets/53850249/6311739b-ed5c-45b5-90bb-06383484916f">

**Comment by eXzacT** [comment]
oh right I forgot to add version 1.2 in the file itsef even though it actually is, as for the fix rotation I'll fix it in a bit

**Comment by eXzacT** [comment]
Should be fine with the latest release 1.2.1, let me know if you encounter any bugs again and thanks for the ticket :)
