### ISSUE TITLE
Redundant meshes

### ISSUE THREAD

**Issue by AVA3d** [eXzacT/RePrimitive#5]
It looks like the addon generates redundant meshes for every changes: 
Video: https://github.com/eXzacT/RePrimitive/assets/84742853/bd6b98be-8403-4c69-bfbb-a001a9808e84

**Comment by eXzacT** [comment]
Oh wow, I thought deleting objects would delete them entirely but yes you are right there's still leftovers in the blender file.
When you click on an object and press delete or x that's the same thing that I am doing with the addon, blender also keeps that data by default.
Let me read more about it and if there's a way to fully delete and I'll get back to you, also thanks for letting me know.

**Comment by AVA3d** [comment]
Yeah, organizing data in Blender is quite tricky. What we see in the View Layer isn't the same what's going on under the hood.
"Blender File" tab suits better for it
