### ISSUE TITLE
RePrimitive 2 Italian and German

### ISSUE THREAD

**Issue by 47b3r70** [eXzacT/RePrimitive#8]
Hi Damjan

In the operators.py file I only translated the labels, it was not necessary for the correct functioning of RePrimitive, only an aesthetic factor.

This morning I tried with the French language, everything OK, with the German language only the Toroid worked.
then I realized that it write sk_SK instead of de_DE, so I made the change to localization.py, changing:
elif user_language == 'sk_SK': in elif user_language == 'de_DE':

I attach some screenshots of the operation in Italian and German, where You will notice that in German everything changes except the labels contained in the operators.py file, which remain in Italian.

I'm glad that You also follow Ponte Ryuurui and Josh Gambrell, True Legends, I Learned a Lot from Them.

Thank You Again for This Fantastic Program.

![CircleITA](https://github.com/eXzacT/RePrimitive/assets/165147591/5d562791-3cf6-45a6-b810-96cbbac9c754)
![CircleDE](https://github.com/eXzacT/RePrimitive/assets/165147591/74b98920-440c-48d3-95cb-e3bd32e3522e)
![ConeITA](https://github.com/eXzacT/RePrimitive/assets/165147591/9d39b237-0b78-47a7-bacf-4b87bc7f1000)
![ConeDE](https://github.com/eXzacT/RePrimitive/assets/165147591/09c9c716-8a02-4913-9208-060cb46b63d6)
![CylinderITA](https://github.com/eXzacT/RePrimitive/assets/165147591/e50311bb-dd00-4176-980c-cc316846c41e)
![CylinderDE](https://github.com/eXzacT/RePrimitive/assets/165147591/cb94dc42-fb56-4a16-b83b-353652ae8dd7)
![IcoSphereITA](https://github.com/eXzacT/RePrimitive/assets/165147591/b74d042d-cd2d-4024-aff9-c6fcb84d2441)
![IcoSphereDE](https://github.com/eXzacT/RePrimitive/assets/165147591/fc5f19c9-6797-4b1c-b105-3de860f23228)
![SphereITA](https://github.com/eXzacT/RePrimitive/assets/165147591/2e537c09-78d2-4db0-b237-46def1e4beca)
![SphereDE](https://github.com/eXzacT/RePrimitive/assets/165147591/3d40e605-b695-405d-85d1-e3517dcf9aa9)
![TorusITA](https://github.com/eXzacT/RePrimitive/assets/165147591/2a47256e-558e-4fdf-914e-26d61a4dcb39)
![TorusDE](https://github.com/eXzacT/RePrimitive/assets/165147591/779a88db-9316-489b-800e-11dcc40472ac)

**Comment by eXzacT** [comment]
Hey, thank you for your help, I fixed it, will be in the next release :)

**Comment by 47b3r70** [comment]
It was an honor and a pleasure.
Thank You
Alberto Battaglia
Andjelkovic Damjan wrote:
Hey, thank you for your help, I fixed it, will be in the next release :)
